export const housingTags = [
  "Apartment",
  "House",
  "Condo",
  "Townhouse",
  "Studio",
  "Duplex",
  "Single Family Home",
  "Multi-Family Home",
  "Furnished",
  "Unfurnished",
  "Pet-Friendly",
  "Utilities Included",
  "Parking",
  "Balcony",
  "Garden",
  "Modern",
  "Vintage",
  "Renovated",
  "Accessible",
  "Near Public Transit",
  "Security System",
  "Laundry Facilities",
  "Air Conditioning",
  "Heating",
  "Dishwasher",
  "Pool",
  "Gym",
  "Elevator",
  "Wheelchair Accessible",
  "Smoke-Free",
  "Fireplace",
  "Storage",
  "Hardwood Floors",
  "Carpet",
  "Tile Floors",
  "chair",
  "desk",
  "lamp",
  "bed",
  "dresser",
  "nightstand",
  "couch",
  "sofa",
  "armchair",
  "coffee table",
  "end table",
  "bookcase",
  "dining table",
  "dining chair",
  "kitchen island",
  "bar stool",
  "bench",
];

export const electronicsTags = [
  "smartphone",
  "laptop",
  "tablet",
  "desktop computer",
  "headphone",
  "speaker",
  "camera",
  "wearable",
  "gaming console",
  "smart tv",
  "home appliance",
  "printer",
  "networking device",
  "accessory",
  "gadget",
  "drone",
  "virtual reality",
  "audio system",
  "security camera",
  "e-reader",
  "portable charger",
  "smart home",
  "smart watch",
  "smart speaker",
  "smart display",
  "mobile",
  "cell phone",
  "iphone",
  "samsung",
];

export const vehiclesTags = [
  "car",
  "motorcycle",
  "bicycle",
  "scooter",
  "truck",
  "van",
  "bus",
  "RV",
  "electric vehicle",
  "hybrid vehicle",
  "sedan",
  "coupe",
  "convertible",
  "SUV",
  "pickup",
  "minivan",
  "off-road vehicle",
  "classic car",
  "sports car",
  "compact car",
  "motorhome",
];
